version: '3.9'

services:
  db-migrator:
    build:
      context: .
      dockerfile: Dockerfile.Production
    image: products-db-migrator:prod
    container_name: products-db-migrator-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production